name: Jira AI Test Case Generator

on:
  # Triggered from Jira Webhook
  repository_dispatch:
    types: [jira-to-github]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Jira AI Test Case Generator
        env:
          JIRA_URL: ${{ vars.JIRA_URL }}
          PROJECT_KEY: ${{ vars.PROJECT_KEY }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python jira_ai_testcases.py
